services:
  telegram-bot:
    build: .
    container_name: daralla-bot
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    environment:
      # Переменные окружения загружаются из .env файла
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_IDS=${ADMIN_ID}
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
      - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
      # Опциональные переменные (могут быть пустыми)
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN:-}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      # Finland серверы


      # Latvia серверы
      - XUI_HOST_LATVIA_1=${XUI_HOST_LATVIA_1}
      - XUI_LOGIN_LATVIA_1=${XUI_LOGIN_LATVIA_1}
      - XUI_PASSWORD_LATVIA_1=${XUI_PASSWORD_LATVIA_1}

      # Netherlands серверы
      - XUI_HOST_NETHERLANDS_1=${XUI_HOST_NETHERLANDS_1}
      - XUI_LOGIN_NETHERLANDS_1=${XUI_LOGIN_NETHERLANDS_1}
      - XUI_PASSWORD_NETHERLANDS_1=${XUI_PASSWORD_NETHERLANDS_1}

      # Estonia серверы

    ports:
      # Открываем порт для webhook'ов YooKassa
      - "5000:5000"
    volumes:
      # Монтируем папку для баз данных
      - ./data:/app/data:rw
      # Монтируем .env файл если он есть
      - ./.env:/app/.env:ro
    networks:
      - bot-network
    # Ограничения ресурсов для продакшена
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  bot-network:
    driver: bridge
